version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Running build..."
      - npm run build

  post_build:
    commands:
      - 'curl https://spine.skytest.io/s/health -o /dev/null -s -w "dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\n"'
      - 'curl https://spine.skytest.io/s/health -o /dev/null -s -w "dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\n"'
      - "curl https://spine.skytest.io/s/preshorten -H 'x-api-key: 9tNPFuvsW77q1iEfARu4O7jXhqDsJ9qd9yVrSqdi' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - "curl https://spine.skytest.io/s/preshorten -H 'x-api-key: 9tNPFuvsW77q1iEfARu4O7jXhqDsJ9qd9yVrSqdi' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - "curl https://shortener.spine.highridge-test.atmoapps.net/preshorten -H 'x-api-key: 4stR2T3M918oWt1GQf8R92yFW5MhXyrj5rc1NbLC' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - "curl https://shortener.spine.highridge-test.atmoapps.net/preshorten -H 'x-api-key: 4stR2T3M918oWt1GQf8R92yFW5MhXyrj5rc1NbLC' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - export OUT_REPO=$CODEBUILD_SRC_DIR_TargetOutput
      - git -C $OUT_REPO checkout $TARGET_BRANCH
      - git -C $OUT_REPO remote -v
      - echo "Last build executed at $(date +%Y-%m-%dT%H:%M:%S)" > $OUT_REPO/info.txt
      - curl -L -o $OUT_REPO/file_example_PNG_1MB.png https://file-examples.com/storage/fe810015e269b01be9e7508/2017/10/file_example_PNG_1MB.png
      - |
        if [ -n "$(git -C $OUT_REPO status --porcelain)" ]; then
          git config --global user.email "codebuild@example.com"
          git config --global user.name "CodeBuild"
          git -C $OUT_REPO add .
          git -C $OUT_REPO commit -m "Build $CODEBUILD_BUILD_NUMBER"
          git -C $OUT_REPO push --set-upstream origin $TARGET_BRANCH
        fi
