version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Running build..."
      - npm run build

  post_build:
    commands:
      - 'curl https://spine.skytest.io/s/health -o /dev/null -s -w "dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\n"'
      - 'curl https://spine.skytest.io/s/health -o /dev/null -s -w "dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\n"'
      - "curl https://spine.skytest.io/s/preshorten -H 'x-api-key: 9tNPFuvsW77q1iEfARu4O7jXhqDsJ9qd9yVrSqdi' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - "curl https://spine.skytest.io/s/preshorten -H 'x-api-key: 9tNPFuvsW77q1iEfARu4O7jXhqDsJ9qd9yVrSqdi' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - "curl https://shortener.spine.highridge-test.atmoapps.net/preshorten -H 'x-api-key: 4stR2T3M918oWt1GQf8R92yFW5MhXyrj5rc1NbLC' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - "curl https://shortener.spine.highridge-test.atmoapps.net/preshorten -H 'x-api-key: 4stR2T3M918oWt1GQf8R92yFW5MhXyrj5rc1NbLC' -H 'Content-Type: application/json' --data '{\"url\": \"https://atmoapps.com\"}' -o /dev/null -s -w \"dns:%{time_namelookup}s connect:%{time_connect}s ssl:%{time_appconnect}s ttfb:%{time_starttransfer}s total:%{time_total}s\\n\""
      - echo "Cloning target repo..."
      - git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${TARGET_REPO_NAME}.git /tmp/target-repo
      - cd /tmp/target-repo
      - git checkout $TARGET_BRANCH || git checkout -b $TARGET_BRANCH
      - git config user.email "codebuild@example.com"
      - git config user.name "CodeBuild"
      - echo "Last build executed at $(date +%Y-%m-%dT%H:%M:%S)" > info.txt
      - git add -A
      - |
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Build output from source repo - $(date +%Y-%m-%dT%H:%M:%S)"
          git push origin $TARGET_BRANCH
        fi
